### PR TITLE
Add svelte documentation

### PR DESCRIPTION
**Pull request by kentng201**
- add installation guide of svelte
- add stores methods of svelte

### CODE REVIEW

**Review by WongYC-66 — APPROVED** [review]

**Comment by WongYC-66** [comment]
LGTM, nice one

**Review by WongYC-66 — COMMENTED** [review]
```
:::info
Please make sure you have go through the [Environment Setup](/docs/environment-setup) before you proceed with the installation.
:::
```
Github md previewer not working for this, lets push to master and see how Docusaurus redner it.

**Comment by kentng201** [comment]
Hmm sure, lets check

**Comment by pockettojs** [comment]
Ya its works
Screenshot 2024-10-27 at 3 15 05 AM
This syntax only works in docurusarus

**Pull request merged**
